const experience = [
  ["2025 - Present", "Software Developer", "visorPRO / T1 Technology", "My current role includes data extraction and ingestion, database updates, and data quality work. I build data connections with Python and SQL, contribute to RAG components using PostgreSQL and AWS, and work on backend and frontend features with Express.js and TypeScript."],
  ["2023 - 2025", "Data Engineer", "Joygame Publishing", "I started as a data analyst intern and later became a data engineer. I maintained Python and Airflow pipelines for more than 20 sources, automated Excel workflows, built API integrations, and worked closely with product, marketing, and finance data. I created more than 30 Tableau dashboards and reduced monthly BigQuery query costs from $300 to $150."],
  ["2022 - 2024", "Teaching & Technical Assistant", "New York Global Institute of Linguistics", "I helped coordinate and teach online linguistics seminars. My work included lesson planning, evaluating assignments, supporting professors, and helping students with syntax and semantics."],
];
const capabilities = [
  ["01", "Data engineering", "Python and Airflow pipelines, API integrations, ETL and ELT work, and data modeling in GCP, BigQuery, AWS, and PostgreSQL."],
  ["02", "Data quality", "Finding the cause of incorrect or missing data, understanding source limitations, documenting processing logic, and keeping production pipelines running."],
  ["03", "Product analytics", "Working with user behavior and business metrics, especially for game, marketing, and finance data. I have built more than 30 Tableau dashboards."],
  ["04", "Software development", "Backend and frontend work with TypeScript and Express.js. This is newer territory for me than data engineering, but I am comfortable learning through real tasks."],
];

export default function Home() {
  return <main>
    <nav className="nav" aria-label="Primary navigation"><a className="wordmark" href="#top" aria-label="Cihan Basoglu, home">CB</a><div className="navLinks"><a href="#work">Work</a><a href="#about">About</a><a href="mailto:cihanbasoglu57@gmail.com">Contact</a></div></nav>
    <section className="hero" id="top"><p className="eyebrow">Data Engineer & Software Developer · Edmonton, Canada</p><h1>I work with data,<br/>software, and analytics.</h1><div className="heroBottom"><p className="intro">I’m Cihan Basoglu. My main area is data engineering, especially Python, SQL, Airflow, and BigQuery. I also work on software development and analytics. I know what I can do well, and I can get up to speed quickly in areas that are newer to me.</p><a className="roundLink" href="#work" aria-label="View my experience"><span>Experience</span><b aria-hidden="true">↓</b></a></div></section>
    <section className="statement" id="about"><p className="sectionLabel">About</p><p className="largeCopy">I build and maintain data pipelines, work with databases, check data quality, and help turn raw data into reports that people can actually use.</p><p className="supportingCopy">Most of my experience is in data engineering and product analytics. I have worked with data from many APIs and platforms, maintained production pipelines, investigated data problems, and explained technical details to different teams. In my current role, I am also gaining more experience in backend and frontend development.</p></section>
    <section className="capabilities" aria-labelledby="capability-title"><div className="sectionHead"><p className="sectionLabel">Skills</p><h2 id="capability-title">What I work with.</h2></div><div>{capabilities.map(([n,title,text])=><article className="capability" key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="experience" id="work"><div className="sectionHead"><p className="sectionLabel">Experience</p><h2>Where I have worked.</h2></div><div>{experience.map(([period,role,company,copy])=><article className="experienceItem" key={company}><p className="period">{period}</p><div><h3>{role}</h3><p className="company">{company}</p></div><p className="experienceCopy">{copy}</p></article>)}</div></section>
    <section className="education"><p className="sectionLabel">Education</p><div><h2>My academic background.</h2><p>I have master’s degrees in Cognitive Science and Linguistics, and a bachelor’s degree in Linguistics. Before moving into data work, I studied language, cognition, and research methods. This background has been useful when I need to understand complicated systems or explain them clearly.</p></div></section>
    <section className="certifications" aria-labelledby="certifications-title"><div className="sectionHead"><p className="sectionLabel">Certifications</p><h2 id="certifications-title">Professional certifications.</h2></div><div className="certificationList"><article className="certification"><p className="certificationYear">2025</p><img className="certificationBadge" src="https://images.credly.com/images/d7d0d0f5-ea0b-4b3f-a76f-93934726573d/twitter_thumb_201604_image.png" alt="Google Cloud Professional Data Engineer certification badge"/><div><h3>Professional Data Engineer</h3><p>Google Cloud</p></div></article><article className="certification"><p className="certificationYear">2024</p><img className="certificationBadge" src="https://images.credly.com/images/ed8e9dd4-2125-4e0b-9db1-57cf67de09d9/image.png" alt="Astronomer Apache Airflow DAG Authoring certification badge"/><div><h3>Apache Airflow DAG Authoring</h3><p>Astronomer</p></div></article></div></section>
    <footer><p className="footerLead">Cihan Basoglu</p><div className="footerActions"><p>Currently working as a Software Developer at visorPRO.</p><a href="mailto:cihanbasoglu57@gmail.com">Email ↗</a><a href="https://www.linkedin.com/in/kjngs/" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="/cv-cihan-basoglu.pdf" target="_blank">Resume ↗</a></div><p className="copyright">© 2026 Cihan Basoglu</p></footer>
  </main>;
}
